[2024-07-30T13:55:01.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-30T13:50:00+00:00 [queued]>
[2024-07-30T13:55:01.374+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-30T13:50:00+00:00 [queued]>
[2024-07-30T13:55:01.374+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-30T13:55:01.387+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-30 13:50:00+00:00
[2024-07-30T13:55:01.392+0000] {standard_task_runner.py:57} INFO - Started process 2464 to run task
[2024-07-30T13:55:01.398+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-30T13:50:00+00:00', '--job-id', '525', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmpnbjx3dcm']
[2024-07-30T13:55:01.401+0000] {standard_task_runner.py:85} INFO - Job 525: Subtask task_validate_submissions
[2024-07-30T13:55:01.490+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-30T13:50:00+00:00 [running]> on host 6bb718ab9b8f
[2024-07-30T13:55:01.595+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T13:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T13:50:00+00:00'
[2024-07-30T13:55:01.597+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-30T13:55:01.609+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  None
[2024-07-30T13:55:01.611+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-07-30T13:55:01.611+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/library/validation_reports.py", line 396, in get_hello
    select_datas(mobile_records[1])
[2024-07-30T13:55:01.611+0000] {logging_mixin.py:151} WARNING - TypeError: 'NoneType' object is not subscriptable
[2024-07-30T13:55:01.612+0000] {logging_mixin.py:151} INFO - Error while fetching data from PostgreSQL 'NoneType' object is not subscriptable None
[2024-07-30T13:55:01.613+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-30T13:55:01.613+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-30T13:55:01.626+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240730T135000, start_date=20240730T135501, end_date=20240730T135501
[2024-07-30T13:55:01.653+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-30T13:55:01.681+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
