[2024-07-29T13:15:01.362+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T13:10:00+00:00 [queued]>
[2024-07-29T13:15:01.370+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T13:10:00+00:00 [queued]>
[2024-07-29T13:15:01.370+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-29T13:15:01.382+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-29 13:10:00+00:00
[2024-07-29T13:15:01.388+0000] {standard_task_runner.py:57} INFO - Started process 9049 to run task
[2024-07-29T13:15:01.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-29T13:10:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmpzylbdsew']
[2024-07-29T13:15:01.399+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask task_validate_submissions
[2024-07-29T13:15:01.462+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T13:10:00+00:00 [running]> on host 3fb5581aee62
[2024-07-29T13:15:01.553+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T13:10:00+00:00'
[2024-07-29T13:15:01.554+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-29T13:15:01.565+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  None
[2024-07-29T13:15:01.566+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-07-29T13:15:01.567+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/library/validation_reports.py", line 367, in get_hello
    select_datas(mobile_records[1])
[2024-07-29T13:15:01.567+0000] {logging_mixin.py:151} WARNING - TypeError: 'NoneType' object is not subscriptable
[2024-07-29T13:15:01.568+0000] {logging_mixin.py:151} INFO - Error while fetching data from PostgreSQL 'NoneType' object is not subscriptable None
[2024-07-29T13:15:01.568+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-29T13:15:01.569+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-29T13:15:01.577+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240729T131000, start_date=20240729T131501, end_date=20240729T131501
[2024-07-29T13:15:01.603+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-29T13:15:01.629+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
