[2024-07-03T09:59:22.250+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [queued]>
[2024-07-03T09:59:22.273+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [queued]>
[2024-07-03T09:59:22.273+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:59:22.287+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-03 03:25:00+00:00
[2024-07-03T09:59:22.298+0000] {standard_task_runner.py:57} INFO - Started process 21019 to run task
[2024-07-03T09:59:22.308+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-03T03:25:00+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmplgdi_x8k']
[2024-07-03T09:59:22.310+0000] {standard_task_runner.py:85} INFO - Job 576: Subtask id_task_get_emails
[2024-07-03T09:59:22.421+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:59:22.667+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T03:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T03:25:00+00:00'
[2024-07-03T09:59:22.668+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:59:22.669+0000] {logging_mixin.py:151} INFO - #>2024-07-03 09:59:22.669292_User@StatDep: EmailRobot in screated.
[2024-07-03T09:59:22.669+0000] {logging_mixin.py:151} INFO - #>2024-07-03 09:59:22.669463_User@StatDep: get_for_recent_emails is started...
[2024-07-03T09:59:22.669+0000] {logging_mixin.py:151} INFO - #>2024-07-03 09:59:22.669580_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T09:59:23.048+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T09:59:23.372+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T09:59:23.372+0000] {logging_mixin.py:151} INFO - #>2024-07-03 09:59:23.372539_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T09:59:23.372+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T09:59:23.408+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240703T032500, start_date=20240703T095922, end_date=20240703T095923
[2024-07-03T09:59:23.476+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T09:59:23.505+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T13:39:46.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [queued]>
[2024-07-03T13:39:46.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [queued]>
[2024-07-03T13:39:46.477+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T13:39:46.493+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-03 03:25:00+00:00
[2024-07-03T13:39:46.499+0000] {standard_task_runner.py:57} INFO - Started process 26298 to run task
[2024-07-03T13:39:46.504+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-03T03:25:00+00:00', '--job-id', '1542', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpy74f2xht']
[2024-07-03T13:39:46.505+0000] {standard_task_runner.py:85} INFO - Job 1542: Subtask id_task_get_emails
[2024-07-03T13:39:46.582+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T03:25:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T13:39:46.676+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T03:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T03:25:00+00:00'
[2024-07-03T13:39:46.677+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T13:39:46.678+0000] {logging_mixin.py:151} INFO - #>2024-07-03 13:39:46.678056_User@StatDep: EmailRobot in screated.
[2024-07-03T13:39:46.678+0000] {logging_mixin.py:151} INFO - #>2024-07-03 13:39:46.678284_User@StatDep: get_for_recent_emails is started...
[2024-07-03T13:39:46.678+0000] {logging_mixin.py:151} INFO - #>2024-07-03 13:39:46.678443_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T13:41:56.254+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 77, in pop3_fetch_emails
    mail = poplib.POP3_SSL(self.host)
  File "/usr/local/lib/python3.8/poplib.py", line 450, in __init__
    POP3.__init__(self, host, port, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 104, in __init__
    self.sock = self._create_socket(timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 453, in _create_socket
    sock = POP3._create_socket(self, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 110, in _create_socket
    return socket.create_connection((self.host, self.port), timeout)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
[2024-07-03T13:41:56.272+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240703T032500, start_date=20240703T133946, end_date=20240703T134156
[2024-07-03T13:41:56.295+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1542 for task id_task_get_emails ([Errno 110] Connection timed out; 26298)
[2024-07-03T13:41:56.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T13:41:56.381+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
