[2024-07-03T09:56:33.421+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T09:56:33.435+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T09:56:33.436+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:56:33.452+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 00:15:00+00:00
[2024-07-03T09:56:33.457+0000] {standard_task_runner.py:57} INFO - Started process 20322 to run task
[2024-07-03T09:56:33.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T00:15:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpp1nxaqdh']
[2024-07-03T09:56:33.466+0000] {standard_task_runner.py:85} INFO - Job 247: Subtask id_task_get_emails
[2024-07-03T09:56:33.544+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:56:33.771+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:15:00+00:00'
[2024-07-03T09:56:33.772+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:56:33.772+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:56:33.790+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T001500, start_date=20240703T095633, end_date=20240703T095633
[2024-07-03T09:56:33.845+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 247 for task id_task_get_emails (name 'json' is not defined; 20322)
[2024-07-03T09:56:33.881+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:56:33.904+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:18.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T12:04:18.067+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T12:04:18.068+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:18.083+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 00:15:00+00:00
[2024-07-03T12:04:18.095+0000] {standard_task_runner.py:57} INFO - Started process 23144 to run task
[2024-07-03T12:04:18.107+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T00:15:00+00:00', '--job-id', '689', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpfmgia8hv']
[2024-07-03T12:04:18.108+0000] {standard_task_runner.py:85} INFO - Job 689: Subtask id_task_get_emails
[2024-07-03T12:04:18.215+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:18.391+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:15:00+00:00'
[2024-07-03T12:04:18.392+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:18.392+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:18.392612_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:18.392+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:18.392860_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:18.393+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:18.393032_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:18.872+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:19.427+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:20.483+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:20.483194_conneciton to db is set.
[2024-07-03T12:04:20.499+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:20.551+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T001500, start_date=20240703T120418, end_date=20240703T120420
[2024-07-03T12:04:20.723+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 689 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23144)
[2024-07-03T12:04:20.795+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:20.855+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:20:27.907+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T12:20:28.036+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [queued]>
[2024-07-03T12:20:28.036+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:20:28.126+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 00:15:00+00:00
[2024-07-03T12:20:28.131+0000] {standard_task_runner.py:57} INFO - Started process 23813 to run task
[2024-07-03T12:20:28.139+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T00:15:00+00:00', '--job-id', '899', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpxyu0dg_1']
[2024-07-03T12:20:28.141+0000] {standard_task_runner.py:85} INFO - Job 899: Subtask id_task_get_emails
[2024-07-03T12:20:28.347+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T00:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:20:28.537+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:15:00+00:00'
[2024-07-03T12:20:28.539+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:20:28.539+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:20:28.539877_User@StatDep: EmailRobot in screated.
[2024-07-03T12:20:28.540+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:20:28.540226_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:20:28.540+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:20:28.540525_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:20:28.955+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:20:29.391+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:20:29.838+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:20:29.838070_conneciton to db is set.
[2024-07-03T12:20:29.850+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:20:29.850735_cursor execution is successful.
[2024-07-03T12:20:29.854+0000] {logging_mixin.py:151} INFO -    Email from 2024-07-03 15:33:52,  Халимзод Исмоил Абдурахмон <ihalimzod@nbt.tj>  with statis 1 and attachement name 1HK.v0.0000.31012024.xlsx uploaded to db
[2024-07-03T12:20:29.864+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:20:29.864841_conneciton to db is set.
[2024-07-03T12:20:29.870+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:20:29.870770_cursor execution is successful.
[2024-07-03T12:20:29.872+0000] {logging_mixin.py:151} INFO -    Email from 2024-07-03 15:33:52,  Халимзод Исмоил Абдурахмон <ihalimzod@nbt.tj>  with statis 5 and attachement name HK.v0.0000.31012024.xlsx uploaded to db
[2024-07-03T12:20:29.934+0000] {logging_mixin.py:151} INFO -    deletion of email after inserting into database +OK message 1 deleted
[2024-07-03T12:20:29.997+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:20:29.997173_User@StatDep: pop3_fetch_emails is successful.
[2024-07-03T12:20:29.997+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:20:30.044+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T001500, start_date=20240703T122028, end_date=20240703T122030
[2024-07-03T12:20:30.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:20:30.208+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
