[2024-07-03T09:57:50.724+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T09:57:50.747+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T09:57:50.748+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:50.799+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 12:15:00+00:00
[2024-07-03T09:57:50.804+0000] {standard_task_runner.py:57} INFO - Started process 20628 to run task
[2024-07-03T09:57:50.830+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T12:15:00+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp5uzi3xjy']
[2024-07-03T09:57:50.831+0000] {standard_task_runner.py:85} INFO - Job 392: Subtask id_task_get_emails
[2024-07-03T09:57:51.021+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:51.224+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T12:15:00+00:00'
[2024-07-03T09:57:51.225+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:51.225+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:51.244+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T121500, start_date=20240703T095750, end_date=20240703T095751
[2024-07-03T09:57:51.257+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 392 for task id_task_get_emails (name 'json' is not defined; 20628)
[2024-07-03T09:57:51.276+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:51.302+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:05:17.128+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T12:05:17.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T12:05:17.146+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:05:17.164+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 12:15:00+00:00
[2024-07-03T12:05:17.170+0000] {standard_task_runner.py:57} INFO - Started process 23445 to run task
[2024-07-03T12:05:17.178+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T12:15:00+00:00', '--job-id', '833', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpxljzrrrn']
[2024-07-03T12:05:17.180+0000] {standard_task_runner.py:85} INFO - Job 833: Subtask id_task_get_emails
[2024-07-03T12:05:17.298+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:05:17.452+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T12:15:00+00:00'
[2024-07-03T12:05:17.453+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:05:17.454+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:17.454504_User@StatDep: EmailRobot in screated.
[2024-07-03T12:05:17.454+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:17.454703_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:05:17.454+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:17.454851_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:05:17.860+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:05:18.321+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:05:18.787+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:05:18.787576_conneciton to db is set.
[2024-07-03T12:05:18.794+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:05:18.812+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T121500, start_date=20240703T120517, end_date=20240703T120518
[2024-07-03T12:05:18.839+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 833 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23445)
[2024-07-03T12:05:18.853+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:05:18.880+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:24:25.066+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T12:24:25.075+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T12:24:25.075+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:24:25.087+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 12:15:00+00:00
[2024-07-03T12:24:25.091+0000] {standard_task_runner.py:57} INFO - Started process 24416 to run task
[2024-07-03T12:24:25.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T12:15:00+00:00', '--job-id', '1174', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmplk3v5s_v']
[2024-07-03T12:24:25.101+0000] {standard_task_runner.py:85} INFO - Job 1174: Subtask id_task_get_emails
[2024-07-03T12:24:25.157+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:24:25.234+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T12:15:00+00:00'
[2024-07-03T12:24:25.235+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:24:25.236+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:25.236168_User@StatDep: EmailRobot in screated.
[2024-07-03T12:24:25.236+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:25.236344_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:24:25.236+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:25.236468_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:24:25.655+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:24:26.047+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:24:26.047+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:26.047700_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:24:26.048+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:24:26.188+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T121500, start_date=20240703T122425, end_date=20240703T122426
[2024-07-03T12:24:26.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:24:26.260+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:47:04.691+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T14:47:04.738+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [queued]>
[2024-07-03T14:47:04.739+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:47:04.780+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 12:15:00+00:00
[2024-07-03T14:47:04.787+0000] {standard_task_runner.py:57} INFO - Started process 28497 to run task
[2024-07-03T14:47:04.821+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T12:15:00+00:00', '--job-id', '2131', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp3zf41szi']
[2024-07-03T14:47:04.822+0000] {standard_task_runner.py:85} INFO - Job 2131: Subtask id_task_get_emails
[2024-07-03T14:47:05.043+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T12:15:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:47:05.311+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T12:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T12:15:00+00:00'
[2024-07-03T14:47:05.312+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:47:05.312+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:05.312585_User@StatDep: EmailRobot in screated.
[2024-07-03T14:47:05.312+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:05.312780_User@StatDep: get_for_recent_emails is started...
[2024-07-03T14:47:05.312+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:05.312930_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T14:47:05.693+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T14:47:06.033+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T14:47:06.034+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:06.034304_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T14:47:06.034+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:47:06.076+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T121500, start_date=20240703T144704, end_date=20240703T144706
[2024-07-03T14:47:06.111+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:47:06.143+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
