[2024-07-25T07:25:02.313+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-25T07:20:00+00:00 [queued]>
[2024-07-25T07:25:02.321+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-25T07:20:00+00:00 [queued]>
[2024-07-25T07:25:02.321+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-25T07:25:02.335+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-25 07:20:00+00:00
[2024-07-25T07:25:02.341+0000] {standard_task_runner.py:57} INFO - Started process 129154 to run task
[2024-07-25T07:25:02.348+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-25T07:20:00+00:00', '--job-id', '8161', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpoe_r9wcx']
[2024-07-25T07:25:02.351+0000] {standard_task_runner.py:85} INFO - Job 8161: Subtask id_task_get_emails
[2024-07-25T07:25:02.547+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-25T07:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-25T07:25:02.775+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T07:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T07:20:00+00:00'
[2024-07-25T07:25:02.777+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-25T07:25:02.778+0000] {logging_mixin.py:151} INFO - #>2024-07-25 07:25:02.778441_User@StatDep: EmailRobot in screated.
[2024-07-25T07:25:02.778+0000] {logging_mixin.py:151} INFO - #>2024-07-25 07:25:02.778635_User@StatDep: get_for_recent_emails is started...
[2024-07-25T07:25:02.778+0000] {logging_mixin.py:151} INFO - #>2024-07-25 07:25:02.778768_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-25T07:27:13.310+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 34, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/library/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/library/emailRobot.py", line 77, in pop3_fetch_emails
    mail = poplib.POP3_SSL(self.host)
  File "/usr/local/lib/python3.8/poplib.py", line 450, in __init__
    POP3.__init__(self, host, port, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 104, in __init__
    self.sock = self._create_socket(timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 453, in _create_socket
    sock = POP3._create_socket(self, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 110, in _create_socket
    return socket.create_connection((self.host, self.port), timeout)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
[2024-07-25T07:27:13.329+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240725T072000, start_date=20240725T072502, end_date=20240725T072713
[2024-07-25T07:27:13.345+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8161 for task id_task_get_emails ([Errno 110] Connection timed out; 129154)
[2024-07-25T07:27:13.380+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-25T07:27:13.417+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
