[2024-07-15T11:35:01.527+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-15T11:30:00+00:00 [queued]>
[2024-07-15T11:35:01.534+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-15T11:30:00+00:00 [queued]>
[2024-07-15T11:35:01.535+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-15T11:35:01.548+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-15 11:30:00+00:00
[2024-07-15T11:35:01.554+0000] {standard_task_runner.py:57} INFO - Started process 39498 to run task
[2024-07-15T11:35:01.558+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-15T11:30:00+00:00', '--job-id', '6378', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp6xbu1zjk']
[2024-07-15T11:35:01.561+0000] {standard_task_runner.py:85} INFO - Job 6378: Subtask id_task_get_emails
[2024-07-15T11:35:01.700+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-15T11:30:00+00:00 [running]> on host 6f4ef5488251
[2024-07-15T11:35:01.851+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T11:30:00+00:00'
[2024-07-15T11:35:01.853+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-15T11:35:01.853+0000] {logging_mixin.py:151} INFO - #>2024-07-15 11:35:01.853624_User@StatDep: EmailRobot in screated.
[2024-07-15T11:35:01.853+0000] {logging_mixin.py:151} INFO - #>2024-07-15 11:35:01.853791_User@StatDep: get_for_recent_emails is started...
[2024-07-15T11:35:01.853+0000] {logging_mixin.py:151} INFO - #>2024-07-15 11:35:01.853922_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-15T11:35:05.939+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 34, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 77, in pop3_fetch_emails
    mail = poplib.POP3_SSL(self.host)
  File "/usr/local/lib/python3.8/poplib.py", line 450, in __init__
    POP3.__init__(self, host, port, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 104, in __init__
    self.sock = self._create_socket(timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 453, in _create_socket
    sock = POP3._create_socket(self, timeout)
  File "/usr/local/lib/python3.8/poplib.py", line 110, in _create_socket
    return socket.create_connection((self.host, self.port), timeout)
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
[2024-07-15T11:35:05.959+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240715T113000, start_date=20240715T113501, end_date=20240715T113505
[2024-07-15T11:35:05.974+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6378 for task id_task_get_emails ([Errno -5] No address associated with hostname; 39498)
[2024-07-15T11:35:05.992+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-15T11:35:06.020+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
