[2024-07-29T06:00:01.465+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T05:55:00+00:00 [queued]>
[2024-07-29T06:00:01.472+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T05:55:00+00:00 [queued]>
[2024-07-29T06:00:01.472+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-29T06:00:01.486+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-29 05:55:00+00:00
[2024-07-29T06:00:01.493+0000] {standard_task_runner.py:57} INFO - Started process 1544 to run task
[2024-07-29T06:00:01.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-29T05:55:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmp9yd1u7oo']
[2024-07-29T06:00:01.505+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask task_validate_submissions
[2024-07-29T06:00:01.555+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T05:55:00+00:00 [running]> on host 3fb5581aee62
[2024-07-29T06:00:01.632+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T05:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T05:55:00+00:00'
[2024-07-29T06:00:01.633+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-29T06:00:01.644+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  None
[2024-07-29T06:00:01.645+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-07-29T06:00:01.646+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/library/validation_reports.py", line 345, in get_hello
    select_datas(mobile_records[1])
[2024-07-29T06:00:01.646+0000] {logging_mixin.py:151} WARNING - TypeError: 'NoneType' object is not subscriptable
[2024-07-29T06:00:01.647+0000] {logging_mixin.py:151} INFO - Error while fetching data from PostgreSQL 'NoneType' object is not subscriptable None
[2024-07-29T06:00:01.647+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-29T06:00:01.647+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-29T06:00:01.659+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240729T055500, start_date=20240729T060001, end_date=20240729T060001
[2024-07-29T06:00:01.709+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-29T06:00:01.742+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
